#!/bin/bash

# 🚀 QUICK START - Rheingau Portal

echo "═══════════════════════════════════════════════════════════════════════════"
echo "         🍇 Rheingau Portal - Quick Start Guide"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "📝 PROJECT SETUP STEPS:"
echo ""
echo "1️⃣  REPOSITORY PRIVAT STELLEN (GitHub Web)"
echo "   - Gehe zu: https://github.com/Deparfloe/my-first-project"
echo "   - Klicke Settings → Visibility → Private → Save"
echo "   - Status: PRIVAT ✅"
echo ""
echo "2️⃣  UMGEBUNGSVARIABLEN SETUP"
echo "   - Kopiere .env.local.example zu .env.local:"
echo "     cp .env.local.example .env.local"
echo "   - Fülle deine Secrets in .env.local ein:"
echo "     * NEXT_PUBLIC_SUPABASE_URL"
echo "     * NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "     * STRIPE_PUBLIC_KEY & SECRET_KEY"
echo "   - .env.local wird automatisch ignoriert (in .gitignore)"
echo ""
echo "3️⃣  ABHÄNGIGKEITEN INSTALLIEREN"
echo "   npm install"
echo ""
echo "4️⃣  DEVELOPMENT SERVER STARTEN"
echo "   npm run dev"
echo ""
echo "5️⃣  IM BROWSER ÖFFNEN"
echo "   http://localhost:3000"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "📂 PROJEKTSTRUKTUR:"
echo ""
echo "src/"
echo "├── app/              # Pages (Homepage, Directory, Events, etc.)"
echo "├── components/       # UI Components (Button, Card, Input)"
echo "├── server/           # Server Actions (API Logic)"
echo "├── lib/              # Libraries (Supabase, Utils)"
echo "├── types/            # TypeScript Definitions"
echo "├── config/           # Configuration"
echo "├── constants/        # Constants & Messages"
echo "└── styles/           # Global CSS"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔐 SICHERHEIT:"
echo ""
echo "✅ .gitignore:         Schützt .env.local (NICHT committen!)"
echo "✅ GitHub:             PRIVAT (nur du kannst sehen)"
echo "✅ Database:           Row-Level Security aktiviert"
echo "✅ Authentication:     Email OTP mit Doppelverifikation"
echo "✅ Secrets:            Nie im Code, immer in .env.local"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 DEPLOYMENT (Vercel):"
echo ""
echo "   1. GitHub mit Vercel verbinden"
echo "   2. Vercel erstellt auto. neuen Project"
echo "   3. Environment Variablen in Vercel setzen"
echo "   4. Deploy!"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 WEITERE INFORMATIONEN:"
echo ""
echo "   - PROJECT_SETUP.md   - Vollständige Projektdokumentation"
echo "   - PRIVACY_GUIDE.md   - Sicherheits- & Privacy-Guide"
echo "   - README.md          - Project README"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
